# Generated by Django 3.2 on 2025-01-15 00:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration_api', '0010_classroom_staff_classrooms_programs_staff_stafftemptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('isStaff', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isSuperuser', models.BooleanField(default=False)),
                ('isFamily', models.BooleanField(default=False)),
                ('lastLogin', models.DateTimeField(null=True)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('tempPassword', models.CharField(max_length=50, null=True)),
                ('resetTempPwd', models.BooleanField(default=False)),
                ('cognitoEnabled', models.BooleanField(default=False)),
                ('isCognitoUser', models.BooleanField(default=False)),
                ('sendEmail', models.BooleanField(default=False)),
                ('sendEmailAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
