# Generated by Django 3.2 on 2025-01-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoey_api', '0037_alter_eventcalendartable_savedoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatehtmltable',
            name='htmlFormat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplatejsontable',
            name='jsonFormat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='surveysettingstable',
            name='questions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useranswertable',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
